### ISSUE TITLE
Usage Tracking 

### ISSUE THREAD

**Issue by jezzsantos** [jezzsantos/automate#71]
For discovery purposes, we need to know how many people are actually using this technology, and since the CLI is currently used in a predominantly offline tool, it will be necessary to integrate some online tracking mechanism.

# Caveats

We are not interested in tracking people or their personal information. We are only interested in understanding their behaviours:
* Whether they are using it to create patterns, and update patterns
* Whether they are using it to create drafts, and applying them to their codebases
* Frequencies of use
* Unique uses of the tool versus repeated uses of the same toolkit or draft
* How many unique users participate end to end on a toolkit -> draft -> codebase

We also have to deal with offline.
* Tracking reports cannot be sent to Cloud when no online connection. We will need to cache them locally

# Solution

- [x] We can do this safely and anonymously by creating a unique user id (per installation of automate on a machine), and using the unique id of the pattern/toolkit and drafts.
- [x] We would have to anonymize any data we collect, which we can do easily with (irreversible) one-way hashes of data values.
- [x] We would have to create a privacy policy outlining what we collect and why
    - [x] We update the privacy policy
- [x] We would have to assume offline use as the default, and cache the usage data locally, and upload only when connected.
    - [x] The data we collect must not be tracked in source-control along with other data
    - [x] Cache reports (rolling cache of 100 max) on disk
- [x] We can offer the user an opt-out option to not track their data, should they object to it
    - [x] We add the option `--collect-usage` to CLI to allow users to opt-out of collecting data (according to the privacy policy)
    - [x] We add the `collect-usage` value to the `automate info` command for use by the Plugin

**Comment by jezzsantos** [comment]
If we pursue Application Insights as the repository for tracking data, then I have a problem with my Azure account:

My problem is that my azure account is locked to a U.S billing credit card, and I live in NZ now, AND my azure account is tied to iapprove.onmicrosoft.com (instead of jezzsantos.onmicrosoft.com). I cannot change iapprove.onmicrosoft.com to anything meaningful, and I cannot change my billing country in Azure.

Two options:

1. Create a new Azure account with my @gmail.com email, and invite my @hotmail.com into it, OR 
2. Live with my @hotmail email on iapprove.onmicrosoft.com and get a US creditcard to bill, or get my billing country changed by MS support.

**Comment by jezzsantos** [comment]
The UserId can be a permanent onetime generated identifier.

Inspiration. Same algorithm as Jetbrains IntelliJ (`PermanentInstallationID.calculateInstallationId`)

Look for the UUID in store, of not there, generate a UUID (eg. `18ab2a40-f2e9-4272-9acb-736a077f7291`
